services:
  db:
    image: postgres:15.7
    ports:
      - ${POSTGRES_PORT:?POSTGRES_PORT is not found}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is not found}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is not found}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
      network: host
    working_dir: /server
    volumes:
      - .:/server
      - dot-pnpm-store:/server/.pnpm-store
      - server-node-modules:/server/node_modules
    ports:
      - ${PORT}:${PORT:?PORT is not found}
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL:?DATABASE_URL is not found}
      DATABASE_URL_TEST: ${DATABASE_URL_TEST:?DATABASE_URL_TEST is not found}
    command: >
      sh -c "
      pnpm db:generate && pnpm db:deploy &&
      pnpm run start:dev
      "
    tty: true
volumes:
  dot-pnpm-store:
  server-node-modules:
  postgres-data:
