# ==============================================================================
# 1. Base Stage
# ==============================================================================
FROM node:20.18-slim AS base

RUN apt-get update && \
    apt-get install -y --no-install-recommends libssl3 wget ca-certificates procps && \
    npm install -g pnpm && \
    rm -rf /var/lib/apt/lists/*

# ==============================================================================
# 2. Dependencies Stage
# ==============================================================================
FROM base AS dependencies

WORKDIR /dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# ==============================================================================
# 3. Final Stage
# ==============================================================================
FROM base AS runner

WORKDIR /server
RUN rm -rf ./node_modules
COPY --from=dependencies /dependencies/node_modules ./node_modules
COPY --from=dependencies /dependencies/package.json ./package.json

CMD [ "pnpm", "run", "start:dev" ]
