# cSpell:word vitest
name: Test
on:
  push:
    branches: [main, stage, develop]
  pull_request:
    branches: [main, stage, develop]

# 同ブランチのテストは重複させない
concurrency:
  group: ${{ github.workflow }}-${{ github.ref.branches }}
  cancel-in-progress: true

env:
  DATABASE_URL: postgresql://test:postgres@localhost:5432/Test_Employee?schema=test

jobs:
  vitest:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: 'test'
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run-lint-test
        uses: ./.github/actions/lint
      - name: run-vitest
        uses: ./.github/actions/vitest
